/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"time"

	v1 "github.com/yametech/fuxi/pkg/apis/fuxi/v1"
	scheme "github.com/yametech/fuxi/pkg/client/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// NodeLivenessesGetter has a method to return a NodeLivenessInterface.
// A group's client should implement this interface.
type NodeLivenessesGetter interface {
	NodeLivenesses(namespace string) NodeLivenessInterface
}

// NodeLivenessInterface has methods to work with NodeLiveness resources.
type NodeLivenessInterface interface {
	Create(*v1.NodeLiveness) (*v1.NodeLiveness, error)
	Update(*v1.NodeLiveness) (*v1.NodeLiveness, error)
	UpdateStatus(*v1.NodeLiveness) (*v1.NodeLiveness, error)
	Delete(name string, options *metav1.DeleteOptions) error
	DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error
	Get(name string, options metav1.GetOptions) (*v1.NodeLiveness, error)
	List(opts metav1.ListOptions) (*v1.NodeLivenessList, error)
	Watch(opts metav1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.NodeLiveness, err error)
	NodeLivenessExpansion
}

// nodeLivenesses implements NodeLivenessInterface
type nodeLivenesses struct {
	client rest.Interface
	ns     string
}

// newNodeLivenesses returns a NodeLivenesses
func newNodeLivenesses(c *FuxiV1Client, namespace string) *nodeLivenesses {
	return &nodeLivenesses{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the nodeLiveness, and returns the corresponding nodeLiveness object, and an error if there is any.
func (c *nodeLivenesses) Get(name string, options metav1.GetOptions) (result *v1.NodeLiveness, err error) {
	result = &v1.NodeLiveness{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("nodelivenesses").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of NodeLivenesses that match those selectors.
func (c *nodeLivenesses) List(opts metav1.ListOptions) (result *v1.NodeLivenessList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.NodeLivenessList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("nodelivenesses").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested nodeLivenesses.
func (c *nodeLivenesses) Watch(opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("nodelivenesses").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a nodeLiveness and creates it.  Returns the server's representation of the nodeLiveness, and an error, if there is any.
func (c *nodeLivenesses) Create(nodeLiveness *v1.NodeLiveness) (result *v1.NodeLiveness, err error) {
	result = &v1.NodeLiveness{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("nodelivenesses").
		Body(nodeLiveness).
		Do().
		Into(result)
	return
}

// Update takes the representation of a nodeLiveness and updates it. Returns the server's representation of the nodeLiveness, and an error, if there is any.
func (c *nodeLivenesses) Update(nodeLiveness *v1.NodeLiveness) (result *v1.NodeLiveness, err error) {
	result = &v1.NodeLiveness{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("nodelivenesses").
		Name(nodeLiveness.Name).
		Body(nodeLiveness).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *nodeLivenesses) UpdateStatus(nodeLiveness *v1.NodeLiveness) (result *v1.NodeLiveness, err error) {
	result = &v1.NodeLiveness{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("nodelivenesses").
		Name(nodeLiveness.Name).
		SubResource("status").
		Body(nodeLiveness).
		Do().
		Into(result)
	return
}

// Delete takes name of the nodeLiveness and deletes it. Returns an error if one occurs.
func (c *nodeLivenesses) Delete(name string, options *metav1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("nodelivenesses").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *nodeLivenesses) DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("nodelivenesses").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched nodeLiveness.
func (c *nodeLivenesses) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.NodeLiveness, err error) {
	result = &v1.NodeLiveness{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("nodelivenesses").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
