/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"time"

	v1 "github.com/yametech/fuxi/pkg/apis/fuxi/v1"
	scheme "github.com/yametech/fuxi/pkg/client/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// WorkloadsesGetter has a method to return a WorkloadsInterface.
// A group's client should implement this interface.
type WorkloadsesGetter interface {
	Workloadses(namespace string) WorkloadsInterface
}

// WorkloadsInterface has methods to work with Workloads resources.
type WorkloadsInterface interface {
	Create(*v1.Workloads) (*v1.Workloads, error)
	Update(*v1.Workloads) (*v1.Workloads, error)
	UpdateStatus(*v1.Workloads) (*v1.Workloads, error)
	Delete(name string, options *metav1.DeleteOptions) error
	DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error
	Get(name string, options metav1.GetOptions) (*v1.Workloads, error)
	List(opts metav1.ListOptions) (*v1.WorkloadsList, error)
	Watch(opts metav1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.Workloads, err error)
	WorkloadsExpansion
}

// workloadses implements WorkloadsInterface
type workloadses struct {
	client rest.Interface
	ns     string
}

// newWorkloadses returns a Workloadses
func newWorkloadses(c *FuxiV1Client, namespace string) *workloadses {
	return &workloadses{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the workloads, and returns the corresponding workloads object, and an error if there is any.
func (c *workloadses) Get(name string, options metav1.GetOptions) (result *v1.Workloads, err error) {
	result = &v1.Workloads{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("workloadses").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of Workloadses that match those selectors.
func (c *workloadses) List(opts metav1.ListOptions) (result *v1.WorkloadsList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.WorkloadsList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("workloadses").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested workloadses.
func (c *workloadses) Watch(opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("workloadses").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a workloads and creates it.  Returns the server's representation of the workloads, and an error, if there is any.
func (c *workloadses) Create(workloads *v1.Workloads) (result *v1.Workloads, err error) {
	result = &v1.Workloads{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("workloadses").
		Body(workloads).
		Do().
		Into(result)
	return
}

// Update takes the representation of a workloads and updates it. Returns the server's representation of the workloads, and an error, if there is any.
func (c *workloadses) Update(workloads *v1.Workloads) (result *v1.Workloads, err error) {
	result = &v1.Workloads{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("workloadses").
		Name(workloads.Name).
		Body(workloads).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *workloadses) UpdateStatus(workloads *v1.Workloads) (result *v1.Workloads, err error) {
	result = &v1.Workloads{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("workloadses").
		Name(workloads.Name).
		SubResource("status").
		Body(workloads).
		Do().
		Into(result)
	return
}

// Delete takes name of the workloads and deletes it. Returns an error if one occurs.
func (c *workloadses) Delete(name string, options *metav1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("workloadses").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *workloadses) DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("workloadses").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched workloads.
func (c *workloadses) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.Workloads, err error) {
	result = &v1.Workloads{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("workloadses").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
