/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	time "time"

	fuxiv1 "github.com/yametech/fuxi/pkg/apis/fuxi/v1"
	versioned "github.com/yametech/fuxi/pkg/client/clientset/versioned"
	internalinterfaces "github.com/yametech/fuxi/pkg/client/informers/externalversions/internalinterfaces"
	v1 "github.com/yametech/fuxi/pkg/client/listers/fuxi/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// WorkloadsInformer provides access to a shared informer and lister for
// Workloadses.
type WorkloadsInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1.WorkloadsLister
}

type workloadsInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewWorkloadsInformer constructs a new informer for Workloads type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewWorkloadsInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredWorkloadsInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredWorkloadsInformer constructs a new informer for Workloads type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredWorkloadsInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.FuxiV1().Workloadses(namespace).List(options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.FuxiV1().Workloadses(namespace).Watch(options)
			},
		},
		&fuxiv1.Workloads{},
		resyncPeriod,
		indexers,
	)
}

func (f *workloadsInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredWorkloadsInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *workloadsInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&fuxiv1.Workloads{}, f.defaultInformer)
}

func (f *workloadsInformer) Lister() v1.WorkloadsLister {
	return v1.NewWorkloadsLister(f.Informer().GetIndexer())
}
