apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: tektonwebhooks.fuxi.nip.io
spec:
  group: fuxi.nip.io
  names:
    kind: TektonWebHook
    listKind: TektonWebHookList
    plural: tektonwebhooks
    singular: tektonwebhook
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        description: TektonWebHook is the Schema for the tektonwebhooks API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: TektonWebHookSpec defines the desired state of TektonWebHook
            properties:
              git:
                type: string
              jobs:
                items:
                  properties:
                    branch:
                      type: string
                    params:
                      items:
                        properties:
                          name:
                            type: string
                          value:
                            type: string
                        type: object
                      type: array
                    pipeline_run:
                      type: string
                  type: object
                type: array
              secret:
                type: string
            type: object
          status:
            description: TektonWebHookStatus defines the observed state of TektonWebHook
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
