// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag at
// 2020-04-14 16:27:45.240194 +0800 CST m=+0.077821573

package docs

import (
	"bytes"
	"encoding/json"
	"strings"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{.Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "laik author",
            "url": "github.com/yametech",
            "email": "laik.lj@me.com"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/workload/api/v1/configmaps": {
            "get": {
                "description": "workload service for list configMaps",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ConfigMaps"
                ],
                "summary": "workload configMaps list",
                "parameters": [
                    {
                        "type": "string",
                        "description": "namespace",
                        "name": "namespace",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"msg\": \"Success\"}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "{\"msg\": \"Failed\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/workload/api/v1/namespaces/:namespace/configmaps/:name": {
            "get": {
                "description": "workload service for get a configMaps detail",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ConfigMaps"
                ],
                "summary": "workload configMaps get",
                "parameters": [
                    {
                        "type": "string",
                        "description": "namespace",
                        "name": "namespace",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "name",
                        "name": "name",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"msg\": \"Success\"}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "{\"msg\": \"Failed\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/workload/api/v1/namespaces/:namespace/resourcequotas/:name": {
            "get": {
                "description": "workload service for get a resource quota detail",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ResourceQuota"
                ],
                "summary": "workload resource quota get",
                "parameters": [
                    {
                        "type": "string",
                        "description": "namespace",
                        "name": "namespace",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "name",
                        "name": "name",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"msg\": \"Success\"}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "{\"msg\": \"Failed\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/workload/api/v1/namespaces/:namespace/services/:name": {
            "get": {
                "description": "workload service for get a service detail",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Service"
                ],
                "summary": "workload service get",
                "parameters": [
                    {
                        "type": "string",
                        "description": "namespace",
                        "name": "namespace",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "name",
                        "name": "name",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"msg\": \"Success\"}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "{\"msg\": \"Failed\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/workload/api/v1/namespaces/{namespace}/persistentvolumeclaims/{name}": {
            "get": {
                "description": "workload service for get a persistent volume claims detail",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "PersistentVolumeClaims"
                ],
                "summary": "workload persistent volume claims get",
                "parameters": [
                    {
                        "type": "string",
                        "description": "namespace",
                        "name": "namespace",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "name",
                        "name": "name",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"msg\": \"Success\"}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "{\"msg\": \"Failed\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/workload/api/v1/namespaces/{namespace}/pods/{name}": {
            "get": {
                "description": "workload service for get a pod detail",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Pod"
                ],
                "summary": "workload pod get",
                "parameters": [
                    {
                        "type": "string",
                        "description": "namespace",
                        "name": "namespace",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "name",
                        "name": "name",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"msg\": \"Success\"}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "{\"msg\": \"Failed\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/workload/api/v1/namespaces/{namespace}/secrets/{name}": {
            "get": {
                "description": "workload service for get a secret detail",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ConfigMap"
                ],
                "summary": "workload secret get",
                "parameters": [
                    {
                        "type": "string",
                        "description": "namespace",
                        "name": "namespace",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "name",
                        "name": "name",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"msg\": \"Success\"}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "{\"msg\": \"Failed\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/workload/api/v1/persistentvolumeclaims": {
            "get": {
                "description": "workload service for list network policy",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "PersistentVolumeClaims"
                ],
                "summary": "workload persistent volume claims list",
                "responses": {
                    "200": {
                        "description": "{\"msg\": \"Success\"}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "{\"msg\": \"Failed\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/workload/api/v1/persistentvolumes": {
            "get": {
                "description": "workload service for list persistent volume",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "PersistentVolume"
                ],
                "summary": "workload persistent volume list",
                "responses": {
                    "200": {
                        "description": "{\"msg\": \"Success\"}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "{\"msg\": \"Failed\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/workload/api/v1/persistentvolumes/{name}": {
            "get": {
                "description": "workload service for get a persistent volume detail",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "PersistentVolume"
                ],
                "summary": "workload persistent volume get",
                "parameters": [
                    {
                        "type": "string",
                        "description": "name",
                        "name": "name",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"msg\": \"Success\"}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "{\"msg\": \"Failed\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/workload/api/v1/pods": {
            "get": {
                "description": "workload service for list pod",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Pod"
                ],
                "summary": "workload pod list",
                "parameters": [
                    {
                        "type": "string",
                        "description": "namespace",
                        "name": "namespace",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"msg\": \"Success\"}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "{\"msg\": \"Failed\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/workload/api/v1/resourcequotas": {
            "get": {
                "description": "workload service for list resource quota",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ResourceQuota"
                ],
                "summary": "workload resource quota list",
                "parameters": [
                    {
                        "type": "string",
                        "description": "namespace",
                        "name": "namespace",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"msg\": \"Success\"}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "{\"msg\": \"Failed\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/workload/api/v1/secrets": {
            "get": {
                "description": "workload service for list secret",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Secret"
                ],
                "summary": "workload secret list",
                "parameters": [
                    {
                        "type": "string",
                        "description": "namespace",
                        "name": "namespace",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"msg\": \"Success\"}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "{\"msg\": \"Failed\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/workload/api/v1/services": {
            "get": {
                "description": "workload service for list service",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Service"
                ],
                "summary": "workload service list",
                "parameters": [
                    {
                        "type": "string",
                        "description": "namespace",
                        "name": "namespace",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"msg\": \"Success\"}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "{\"msg\": \"Failed\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/workload/apis/apiextensions.k8s.io/v1beta1/customresourcedefinitions": {
            "get": {
                "description": "workload service for list custom resource definition",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "CustomResourceDefinition"
                ],
                "summary": "workload custom resource definition list",
                "parameters": [
                    {
                        "type": "string",
                        "description": "namespace",
                        "name": "namespace",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"msg\": \"Success\"}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "{\"msg\": \"Failed\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/workload/apis/apiextensions.k8s.io/v1beta1/customresourcedefinitions/{name}": {
            "get": {
                "description": "workload service for get a custom resource definition detail",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "CustomResourceDefinition"
                ],
                "summary": "workload custom resource definition get",
                "parameters": [
                    {
                        "type": "string",
                        "description": "namespace",
                        "name": "namespace",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "name",
                        "name": "name",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"msg\": \"Success\"}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "{\"msg\": \"Failed\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/workload/apis/apps/v1/daemonsets": {
            "get": {
                "description": "workload service for list cronJob",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "DaemonSet"
                ],
                "summary": "workload daemonSet list",
                "parameters": [
                    {
                        "type": "string",
                        "description": "namespace",
                        "name": "namespace",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"msg\": \"Success\"}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "{\"msg\": \"Failed\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/workload/apis/apps/v1/namespaces/:namespace/statefulsets/:name": {
            "get": {
                "description": "workload service for get a cronJob detail",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "StatefulSet"
                ],
                "summary": "workload statefulSet get",
                "parameters": [
                    {
                        "type": "string",
                        "description": "namespace",
                        "name": "namespace",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "name",
                        "name": "name",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"msg\": \"Success\"}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "{\"msg\": \"Failed\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/workload/apis/apps/v1/statefulsets": {
            "get": {
                "description": "workload service for list cronJob",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "StatefulSet"
                ],
                "summary": "workload statefulSet list",
                "parameters": [
                    {
                        "type": "string",
                        "description": "namespace",
                        "name": "namespace",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"msg\": \"Success\"}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "{\"msg\": \"Failed\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/workload/apis/autoscaling/v2beta1/horizontalpodautoscalers": {
            "get": {
                "description": "workload service for list horizontal pod autoscaler",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "HorizontalPodAutoscaler"
                ],
                "summary": "workload horizontal pod autoscaler list",
                "parameters": [
                    {
                        "type": "string",
                        "description": "namespace",
                        "name": "namespace",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"msg\": \"Success\"}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "{\"msg\": \"Failed\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/workload/apis/autoscaling/v2beta1/namespaces/{namespace}/horizontalpodautoscalers/{name}": {
            "get": {
                "description": "workload service for get a horizontal pod autoscaler detail",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "HorizontalPodAutoscaler"
                ],
                "summary": "workload horizontal pod autoscaler get",
                "parameters": [
                    {
                        "type": "string",
                        "description": "namespace",
                        "name": "namespace",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "name",
                        "name": "name",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"msg\": \"Success\"}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "{\"msg\": \"Failed\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/workload/apis/batch/v1/jobs": {
            "get": {
                "description": "workload service for list cronJob",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Job"
                ],
                "summary": "workload daemonSet list",
                "parameters": [
                    {
                        "type": "string",
                        "description": "namespace",
                        "name": "namespace",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"msg\": \"Success\"}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "{\"msg\": \"Failed\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/workload/apis/batch/v1/namespaces/:namespace/jobs/:name": {
            "get": {
                "description": "workload service for get a cronJob detail",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Job"
                ],
                "summary": "workload daemonSet get",
                "parameters": [
                    {
                        "type": "string",
                        "description": "namespace",
                        "name": "namespace",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "name",
                        "name": "name",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"msg\": \"Success\"}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "{\"msg\": \"Failed\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/workload/apis/batch/v1beta1/cronjobs": {
            "get": {
                "description": "workload service for list cronJob",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "CronJob"
                ],
                "summary": "workload cronJob list",
                "parameters": [
                    {
                        "type": "string",
                        "description": "namespace",
                        "name": "namespace",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"msg\": \"Success\"}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "{\"msg\": \"Failed\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/workload/apis/batch/v1beta1/deployment": {
            "get": {
                "description": "workload service for list cronJob",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Deployment"
                ],
                "summary": "workload deployment list",
                "parameters": [
                    {
                        "type": "string",
                        "description": "namespace",
                        "name": "namespace",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"msg\": \"Success\"}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "{\"msg\": \"Failed\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/workload/apis/crd/:group/:version/:resource": {
            "get": {
                "description": "workload service for list general custom resource definition",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "GeneralCustomResourceDefinition"
                ],
                "summary": "workload general custom resource definition list",
                "parameters": [
                    {
                        "type": "string",
                        "description": "group",
                        "name": "group",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "version",
                        "name": "version",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "resource",
                        "name": "resource",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"msg\": \"Success\"}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "{\"msg\": \"Failed\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/workload/apis/extensions/v1beta1/ingresses": {
            "get": {
                "description": "workload service for list ingress",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Ingress"
                ],
                "summary": "workload ingress list",
                "parameters": [
                    {
                        "type": "string",
                        "description": "namespace",
                        "name": "namespace",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"msg\": \"Success\"}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "{\"msg\": \"Failed\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/workload/apis/extensions/v1beta1/namespaces/:namespace/ingresses/:name": {
            "get": {
                "description": "workload service for get a ingress detail",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Ingress"
                ],
                "summary": "workload ingress get",
                "parameters": [
                    {
                        "type": "string",
                        "description": "namespace",
                        "name": "namespace",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "name",
                        "name": "name",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"msg\": \"Success\"}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "{\"msg\": \"Failed\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/workload/apis/networking.k8s.io/v1/namespaces/{namespace}/networkpolicies/{name}": {
            "get": {
                "description": "workload service for get a network policy detail",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "NetworkPolicy"
                ],
                "summary": "workload network policy get",
                "parameters": [
                    {
                        "type": "string",
                        "description": "namespace",
                        "name": "namespace",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "name",
                        "name": "name",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"msg\": \"Success\"}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "{\"msg\": \"Failed\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/workload/apis/networking.k8s.io/v1/networkpolicies": {
            "get": {
                "description": "workload service for list network policy",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "NetworkPolicy"
                ],
                "summary": "workload network policy list",
                "parameters": [
                    {
                        "type": "string",
                        "description": "namespace",
                        "name": "namespace",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"msg\": \"Success\"}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "{\"msg\": \"Failed\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/workload/apis/storage.k8s.io/v1beta1/storageclasses": {
            "get": {
                "description": "workload service for list storage class",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "StorageClass"
                ],
                "summary": "workload storage class list",
                "parameters": [
                    {
                        "type": "string",
                        "description": "namespace",
                        "name": "namespace",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"msg\": \"Success\"}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "{\"msg\": \"Failed\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/workload/apis/storage.k8s.io/v1beta1/storageclasses/{name}": {
            "get": {
                "description": "workload service for get a storage class detail",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "StorageClass"
                ],
                "summary": "workload storage class get",
                "parameters": [
                    {
                        "type": "string",
                        "description": "namespace",
                        "name": "namespace",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "name",
                        "name": "name",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"msg\": \"Success\"}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "{\"msg\": \"Failed\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/workload/v1/:ns/cronjobs/:name/get": {
            "get": {
                "description": "workload service for get a cronJob detail",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "CronJob"
                ],
                "summary": "workload cronJob get",
                "parameters": [
                    {
                        "type": "string",
                        "description": "namespace",
                        "name": "namespace",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "name",
                        "name": "name",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"msg\": \"Success\"}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "{\"msg\": \"Failed\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/workload/v1/:ns/deployment/:name/get": {
            "get": {
                "description": "workload service for get a cronJob detail",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Deployment"
                ],
                "summary": "workload cronJob get",
                "parameters": [
                    {
                        "type": "string",
                        "description": "namespace",
                        "name": "namespace",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "name",
                        "name": "name",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"msg\": \"Success\"}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "{\"msg\": \"Failed\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/workload/v1/namespace/:namespace/daemonsets/:name": {
            "get": {
                "description": "workload service for get a cronJob detail",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "DaemonSet"
                ],
                "summary": "workload daemonSet get",
                "parameters": [
                    {
                        "type": "string",
                        "description": "namespace",
                        "name": "namespace",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "name",
                        "name": "name",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"msg\": \"Success\"}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "{\"msg\": \"Failed\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "1.0",
	Host:        "",
	BasePath:    "",
	Schemes:     []string{},
	Title:       "Gin swagger",
	Description: "Gin swagger base",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
