name: fuxi
on:
  push:
    branches:
      - master
      - release-*
    tags:
      - v*
  pull_request:
    branches:
      - master
      - release-*
jobs:
  build:
    name: Build ${{ matrix.target_os }}
    runs-on: ${{ matrix.os }}
    env:
      GOVER: 1.13.5
      GOOS: ${{ matrix.target_os }}
      GOPROXY: https://proxy.golang.org
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        target_amd64: [amd64]
        include:
          - os: ubuntu-latest
            target_os: linux
          - os: windows-latest
            target_os: windows
    steps:
      - name: Set up Go ${{ env.GOVER }}
        uses: actions/setup-go@v1
        with:
          go-version: ${{ env.GOVER }}
      - name: Install golangci-lint
        run: |
          curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b "${{ env.GOROOT }}/bin" v1.21.0
#      - name: Check out code into the Go module directory
#        uses: actions/checkout@v1
      # - name: Run make lint
      #   run: make check
      - name: Run make build
        run: go build  ./cmd/ops
