name: fuxi
on:
  push:
    branches:
      - master
      - release-*
    tags:
      - v*
  pull_request:
    branches:
      - master
      - release-*
jobs:
  build:
    name: Build ${{ matrix.target_os }}
    runs-on: ${{ matrix.os }}
    env:
      GOVER: 1.14.0
      GOOS: ${{ matrix.target_os }}
      GOPROXY: https://proxy.golang.org
      GO111MODULE: on
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
        target_amd64: [amd64]
        include:
          - os: ubuntu-latest
            target_os: linux
          - os: macOS-latest
            target_os: darwin
          - os: windows-latest
            target_os: windows
    steps:
      - name: Set up Go ${{ env.GOVER }}
        uses: actions/setup-go@v1
        with:
          go-version: 1.14
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install golangci-lint
        run: curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b "${{ env.GOROOT }}/bin" v1.21.0
      - name: make build
        run:  make build